[package]
name = "terminal-mode-control"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.12.1"
parking_lot = "0.12.3"
winapi = { version = "0.3.9", features = ["synchapi", "winerror"] }
